# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b814f825050491cf196140a31e4df9aec5362f190f81706fd107b519348c8e2ffa447e36fad10eac5877c430ac340dc97da6dd8325792dc39ef479b3451426fd

test:
  secret_key_base: 4ab8e1694e8f3f7426a8c2260454791b0f5c4b3b3b5b598ce8dbaa378b257556e1ae88ae7cb4934f838346d609e63e39ae0fc842dd84c278d932b2888d793a76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
